const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
window.addEventListener('load',()=>setTimeout(()=>$('#loader').classList.add('hide'),550));
$('#year').textContent=new Date().getFullYear();
const saved=localStorage.getItem('ss-theme'); if(saved==='light') document.body.classList.add('light');
$('#theme').addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('ss-theme',document.body.classList.contains('light')?'light':'dark')});
$('#menu').addEventListener('click',()=>$('.nav nav').classList.toggle('open')); $$('.nav nav a').forEach(a=>a.addEventListener('click',()=>$('.nav nav').classList.remove('open')));
window.addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',((e.clientX/innerWidth)-.5)*2);document.documentElement.style.setProperty('--my',((e.clientY/innerHeight)-.5)*2)});
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12}); $$('.reveal').forEach(x=>obs.observe(x));
if(matchMedia('(hover:hover)').matches){$$('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateY(${x*10}deg) rotateX(${-y*10}deg) translateY(-5px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
$$('.cert').forEach(c=>c.addEventListener('click',e=>{if(!e.target.closest('a'))c.classList.toggle('flipped')}));
const words=['EEE Student','Problem Solver','C Programmer','Technology Explorer'];let wi=0,ci=0,del=false;function type(){const w=words[wi],el=$('#typed');el.textContent=w.slice(0,ci);if(!del&&ci<w.length)ci++;else if(del&&ci>0)ci--;else if(ci===w.length){del=true;return setTimeout(type,1100)}else{del=false;wi=(wi+1)%words.length}setTimeout(type,del?45:80)}type();
$$('.photo').forEach((p,i)=>{const like=$('.like',p),count=$('span',like),form=$('.commentForm',p),comments=$('.comments',p),key='ss-photo-'+i;let data;try{data=JSON.parse(localStorage.getItem(key))||{liked:false,count:0,comments:[]}}catch{data={liked:false,count:0,comments:[]}};function render(){like.classList.toggle('active',data.liked);like.firstChild.nodeValue=data.liked?'♥ ':'♡ ';count.textContent=data.count;comments.innerHTML=data.comments.map(x=>`<p>${x.replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]))}</p>`).join('');localStorage.setItem(key,JSON.stringify(data))}like.addEventListener('click',()=>{data.liked=!data.liked;data.count=Math.max(0,data.count+(data.liked?1:-1));render()});$('.commentToggle',p).addEventListener('click',()=>form.classList.toggle('show'));form.addEventListener('submit',e=>{e.preventDefault();const input=$('input',form),v=input.value.trim();if(v){data.comments.push(v.slice(0,120));input.value='';render()}});render()});
const cv=$('#particles'),ctx=cv.getContext('2d');let dots=[];function size(){cv.width=innerWidth*devicePixelRatio;cv.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);dots=Array.from({length:Math.min(80,Math.floor(innerWidth/15))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,z:Math.random()*1+.2,s:Math.random()*1.4+.3}))}size();addEventListener('resize',size);function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#f20d20';for(const d of dots){d.y-=d.z*.28;if(d.y<0)d.y=innerHeight;ctx.globalAlpha=.12+d.z*.28;ctx.beginPath();ctx.arc(d.x,d.y,d.s*d.z,0,7);ctx.fill()}requestAnimationFrame(draw)}if(!matchMedia('(prefers-reduced-motion: reduce)').matches)draw();
